### ISSUE TITLE
BOM and footprints wrong

### ISSUE THREAD

**Issue by olDirdey** [rsheldiii/doom-keycap-hardware#1]
1) can´t find D2 on the PCB. Not needed?
2) C1 / C4 and C17 are 0603 size components and not 0402 like in your .csv document

**Comment by rsheldiii** [comment]
My apologies, this is caused by older gerber files #2.

I've uploaded the correct gerber files, if you use those instead you won't find these issues. D2 is a schottky diode to prevent current entering the USB bus, so it can be omitted
