### ISSUE TITLE
provided Gerber files are older than the project

### ISSUE THREAD

**Issue by olDirdey** [rsheldiii/doom-keycap-hardware#2]
![grafik](https://github.com/rsheldiii/doom-keycap-hardware/assets/17804482/a0b80817-105d-4c6c-b1de-445de972bd70)

![grafik](https://github.com/rsheldiii/doom-keycap-hardware/assets/17804482/6e4f6110-a8f6-4382-8249-d37dc50872ed)

**Comment by zipplet** [comment]
Confirmed in Kicad, the pregenerated Gerber files in the JLCPCB folder are **incorrect**. The Kicad project is different. Please correct the pregenerated gerbers, people will order the wrong board.

Correct board layout from Kicad:

![image](https://github.com/rsheldiii/doom-keycap-hardware/assets/316735/ae60cedc-f849-4b82-abd1-a135e84d06ed)

**Comment by olDirdey** [comment]
> ...people will order the wrong board.

Sure, that's how the error was first noticed. Isn't even usable. 

![grafik](https://github.com/rsheldiii/doom-keycap-hardware/assets/17804482/a60b97c7-5203-4a40-b88a-34580fddeed8)

**Comment by rsheldiii** [comment]
My apologies, I've updated the gerbers and they are now current to the kicad project. 

I'm sorry @olDirdey. The pads are all there, but you won't be able to get video out of that board without some incredibly tricky soldering. You could still use the board as a test bed:

1. Verify you don't have any shorts in your soldering with a benchtop power supply. Reflow soldering is pretty tricky, I had several boards that just never worked
2. Verify USB posts by plugging into a computer - this is a half-step, it tells you that the RP2040 and some supporting components are functional
3. Verify flashing works - when everything is functioning properly, the LED will settle into a quick flash loop, indicating rendered frames. If the LED only comes on once, the firmware isn't being loaded at all or the crystal isn't synchronizing in time for the RP2040 to read from flash; if the LED comes on a few times, odds are the WAD file isn't burned / is misaligned. 

Getting to that quick flash state indicates a working board which is no small feat. Again, sorry for the trouble.
